/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { 
  CreditCard, Plus, Trash2, Search, Filter, Loader2, Printer, Check, X, FileText, ChevronDown, Calendar, Mail, DollarSign, Clock, AlertCircle, Download, QrCode
} from 'lucide-react';
import { Invoice, InvoiceItem } from '../types.js';

interface InvoiceGeneratorProps {
  token: string | null;
}

export default function InvoiceGenerator({ token }: InvoiceGeneratorProps) {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeStatus, setActiveStatus] = useState('All');

  // Create Modal State
  const [showModal, setShowModal] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [clientName, setClientName] = useState('');
  const [clientEmail, setClientEmail] = useState('');
  const [clientAddress, setClientAddress] = useState('');
  const [dueDate, setDueDate] = useState('');
  const [currency, setCurrency] = useState('USD');
  const [taxRate, setTaxRate] = useState(5); // %
  const [discountRate, setDiscountRate] = useState(0); // %
  const [notes, setNotes] = useState('');
  
  // Invoice items state
  const [items, setItems] = useState<Omit<InvoiceItem, 'id' | 'amount'>[]>([
    { description: 'Consulting Services', quantity: 10, rate: 120 }
  ]);

  // Preview Print view state
  const [previewInvoice, setPreviewInvoice] = useState<Invoice | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const faqData = [
    {
      q: "Is it legal to create your own invoice?",
      a: "Yes, it is entirely legal to create and issue your own invoices for products or services. Solopreneurs, freelancers, and businesses use custom invoice generators or template creators to format professional billing sheets."
    },
    {
      q: "Can I just create an invoice?",
      a: "Absolutely! You can use our simple invoice generator to create custom, professional invoices online. Simply fill out your client's details, itemize your services, and export a clean PDF."
    },
    {
      q: "What's the difference between an invoice and a bill?",
      a: "An invoice is sent by a business or freelancer to request payment from a client. A bill is the document received by the client that displays the total outstanding balance due to be paid."
    },
    {
      q: "What are common invoice mistakes?",
      a: "Common mistakes include missing payment terms, incorrect client address, lacking an itemized breakdown of rates and quantities, and not providing clear wire or payment details."
    },
    {
      q: "What is the best format for an invoice?",
      a: "A PDF format is universally recognized as the best format for sending invoices because it secures the document's design, layout, and values from unexpected alterations."
    },
    {
      q: "What apps can I use to create an invoice?",
      a: "You can use Secura's free invoice maker app or freelancer invoice generator software. Other applications include Google Docs, Microsoft Word, or complex bookkeeping tools like QuickBooks."
    },
    {
      q: "How to generate a self-invoice?",
      a: "A self-invoice is generated by the buyer rather than the supplier. This happens when the buyer assumes the billing responsibility and formats the document with both company tax details."
    },
    {
      q: "Is Google invoice free?",
      a: "While Google offers basic free document templates inside Google Docs or Sheets, they lack automated calculations. Secura is a dedicated, 100% free online invoice generator."
    },
    {
      q: "Which invoice apps are free?",
      a: "Secura is the best invoice app free of subscription fees. It includes a high-powered freelancer invoice generator and PDF exporter with zero premium upgrades."
    },
    {
      q: "How do I make an invoice on Google?",
      a: "You can search for basic templates inside Google Workspace. However, using a specialized tool like Secura makes it simple to key in tax, discounts, and itemized calculations instantly."
    },
    {
      q: "How to invoice without fees?",
      a: "By using Secura's free invoice generator software, you can generate and print unlimited billing sheets without paying subscription fees or transaction processing costs."
    },
    {
      q: "Can I create an invoice on my phone?",
      a: "Yes, Secura is built with a responsive layout, meaning you can create, preview, and download custom client invoices directly from any mobile or tablet device."
    },
    {
      q: "Can I send invoices through Google?",
      a: "Yes, you can generate a high-quality PDF on Secura, download it to your device, and email it directly as an attachment through your Gmail account."
    },
    {
      q: "How do I make an invoice on my laptop?",
      a: "Open Secura in your laptop browser, click 'Create Invoice', enter your billable line items and client email, and tap 'Generate' to download your tax-ready sheet."
    },
    {
      q: "How do I generate my own invoice?",
      a: "Use our simple invoice generator. Fill in your sender profile details, insert the receiver's name and address, define your rates, and download the document as PDF."
    },
    {
      q: "How to create an invoice simple?",
      a: "Using Secura's online simple invoice maker: enter the billing amount, client details, notes, and hit save. Our server auto-computes taxes and formats the document cleanly."
    }
  ];

  const jsonLdData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqData.map(item => ({
      "@type": "Question",
      "name": item.q,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": `<p>${item.a}</p>`
      }
    }))
  };

  const loadInvoices = async () => {
    if (!token) return;
    setLoading(true);
    try {
      const res = await fetch('/api/invoices', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setInvoices(data);
      }
    } catch (e) {
      console.error('Failed to load invoices:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadInvoices();
  }, [token]);

  // Items manipulation helpers
  const handleAddItem = () => {
    setItems([...items, { description: '', quantity: 1, rate: 0 }]);
  };

  const handleRemoveItem = (index: number) => {
    if (items.length === 1) return;
    setItems(items.filter((_, i) => i !== index));
  };

  const handleItemChange = (index: number, field: string, value: any) => {
    const updated = [...items];
    if (field === 'quantity') {
      updated[index].quantity = Number(value) || 0;
    } else if (field === 'rate') {
      updated[index].rate = Number(value) || 0;
    } else {
      updated[index].description = value;
    }
    setItems(updated);
  };

  // Submit Invoice
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Explicit, clear custom validation checks to provide feedback to the user
    if (!clientName.trim()) {
      setFormError('Please enter the Client Name.');
      return;
    }
    if (!clientEmail.trim()) {
      setFormError('Please enter the Client Email.');
      return;
    }
    // Simple email regex validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(clientEmail.trim())) {
      setFormError('Please enter a valid Client Email address.');
      return;
    }
    if (!dueDate) {
      setFormError('Please select a valid Due Date.');
      return;
    }
    if (!items || items.length === 0) {
      setFormError('Please add at least one line item to the invoice.');
      return;
    }

    // Validate each line item individually
    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      if (!item.description || !item.description.trim()) {
        setFormError(`Please provide a description for line item #${i + 1}.`);
        return;
      }
      if (item.quantity === undefined || item.quantity <= 0) {
        setFormError(`Please specify a quantity greater than 0 for "${item.description || `item #${i + 1}`}".`);
        return;
      }
      if (item.rate === undefined || item.rate < 0) {
        setFormError(`Please specify a rate greater than or equal to 0 for "${item.description || `item #${i + 1}`}".`);
        return;
      }
    }

    setFormError(null);

    const payload = {
      clientName: clientName.trim(),
      clientEmail: clientEmail.trim(),
      clientAddress,
      dueDate,
      items,
      taxRate,
      discountRate,
      currency,
      notes
    };

    try {
      const res = await fetch('/api/invoices', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        setShowModal(false);
        resetForm();
        loadInvoices();
      } else {
        const data = await res.json();
        setFormError(data.error || 'Failed to create invoice.');
      }
    } catch (e: any) {
      console.error('Invoice creation failed:', e);
      setFormError(e.message || 'Network error occurred. Please try again.');
    }
  };

  // Mark status paid/sent
  const handleUpdateStatus = async (id: string, status: 'paid' | 'sent') => {
    try {
      const res = await fetch(`/api/invoices/${id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ status })
      });
      if (res.ok) {
        loadInvoices();
        if (previewInvoice && previewInvoice.id === id) {
          setPreviewInvoice({ ...previewInvoice, status });
        }
      }
    } catch (e) {
      console.error('Failed to update status:', e);
    }
  };

  // Delete invoice
  const handleDelete = async (id: string) => {
    try {
      const res = await fetch(`/api/invoices/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        setPreviewInvoice(null);
        loadInvoices();
      }
    } catch (e) {
      console.error('Failed to delete invoice:', e);
    }
  };

  const resetForm = () => {
    setClientName('');
    setClientEmail('');
    setClientAddress('');
    setDueDate('');
    setCurrency('USD');
    setTaxRate(5);
    setDiscountRate(0);
    setNotes('');
    setItems([{ description: 'Consulting Services', quantity: 10, rate: 120 }]);
    setFormError(null);
  };

  // Currency map symbols
  const getCurrencySymbol = (cur: string) => {
    if (cur === 'EUR') return '€';
    if (cur === 'GBP') return '£';
    return '$';
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = (invoice: any) => {
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Invoice ${invoice.invoiceNumber}</title>
  <style>
    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      color: #000;
      background-color: #fff;
      margin: 0;
      padding: 40px;
      line-height: 1.4;
    }
    .invoice-box {
      max-width: 800px;
      margin: auto;
      border: 1px solid #ddd;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
      padding: 30px;
      border-radius: 8px;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 2px solid #000;
      padding-bottom: 20px;
      margin-bottom: 20px;
    }
    .header h1 {
      margin: 0;
      font-size: 28px;
      font-weight: 900;
      letter-spacing: -1px;
    }
    .meta-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      font-size: 12px;
      margin-bottom: 20px;
    }
    .meta-col h3 {
      margin: 0 0 8px 0;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #666;
    }
    .info-line {
      display: flex;
      margin-bottom: 4px;
    }
    .info-label {
      font-weight: bold;
      width: 120px;
    }
    .divider {
      border-top: 1px solid #000;
      margin: 20px 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
      margin: 20px 0;
    }
    th, td {
      border: 1px solid #000;
      padding: 8px;
      text-align: left;
    }
    th {
      background-color: #f9f9f9;
      font-weight: bold;
    }
    .text-right {
      text-align: right;
    }
    .text-center {
      text-align: center;
    }
    .totals {
      width: 300px;
      margin-left: auto;
      font-size: 12px;
    }
    .totals-line {
      display: flex;
      justify-content: space-between;
      border-bottom: 1px solid #ddd;
      padding: 4px 0;
    }
    .totals-grand {
      border-bottom: 4px double #000;
      font-weight: bold;
      font-size: 14px;
      padding: 6px 0;
    }
    .notes {
      font-size: 11px;
      font-style: italic;
      color: #555;
      background-color: #f9f9f9;
      padding: 10px;
      border-radius: 4px;
      border: 1px solid #ddd;
      margin-top: 20px;
    }
    .footer {
      border-top: 1px solid #ddd;
      padding-top: 20px;
      margin-top: 40px;
      display: flex;
      justify-content: space-between;
      font-size: 10px;
      color: #888;
    }
    @media print {
      body { padding: 0; }
      .invoice-box { border: none; box-shadow: none; padding: 0; }
      .no-print { display: none; }
    }
    .print-btn {
      display: inline-block;
      background: #000;
      color: #fff;
      padding: 8px 16px;
      border-radius: 4px;
      text-decoration: none;
      font-weight: bold;
      font-size: 12px;
      margin-bottom: 20px;
      cursor: pointer;
      border: none;
    }
  </style>
</head>
<body>
  <div class="invoice-box">
    <button class="print-btn no-print" onclick="window.print()">Print / Save as PDF</button>
    <div class="header">
      <div>
        <h1 style="text-transform: uppercase;">SECURA<br>INVOICE</h1>
      </div>
      <div style="text-align: right; font-size: 10px; color: #666;">
        <div style="font-weight: bold; font-size: 12px; color: #000;">Secura Inc.</div>
        <div>VAT-US-8920193</div>
        <div>support@secura.io</div>
      </div>
    </div>
    
    <div class="meta-grid">
      <div class="meta-col">
        <h3>Sender</h3>
        <div class="info-line"><span class="info-label">Company:</span><span>Secura Inc.</span></div>
        <div class="info-line"><span class="info-label">Address:</span><span>75 Financial Plaza, Suite 400</span></div>
        <div class="info-line"><span class="info-label">City:</span><span>10005 New York, US</span></div>
      </div>
      <div class="meta-col">
        <h3>Bill To</h3>
        <div class="info-line"><span class="info-label">Client Name:</span><span>\${invoice.clientName}</span></div>
        <div class="info-line"><span class="info-label">Email:</span><span>\${invoice.clientEmail}</span></div>
        <div class="info-line"><span class="info-label">Address:</span><span>\${invoice.clientAddress || '742 Evergreen Terrace'}</span></div>
      </div>
    </div>

    <div class="divider"></div>

    <div class="meta-grid">
      <div class="info-line"><span class="info-label">Invoice No:</span><strong>\${invoice.invoiceNumber}</strong></div>
      <div class="info-line"><span class="info-label">Created Date:</span><span>\${invoice.createdDate}</span></div>
      <div class="info-line"><span class="info-label">Due Date:</span><span>\${invoice.dueDate}</span></div>
      <div class="info-line"><span class="info-label">Currency:</span><span>\${invoice.currency}</span></div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th class="text-center" style="width: 80px;">Quantity</th>
          <th class="text-right" style="width: 120px;">Unit Price</th>
          <th class="text-right" style="width: 140px;">Amount</th>
        </tr>
      </thead>
      <tbody>
        \${invoice.items.map((itm: any) => \`
          <tr>
            <td>\${itm.description}</td>
            <td class="text-center">\${itm.quantity}</td>
            <td class="text-right">\${getCurrencySymbol(invoice.currency)}\${itm.rate.toFixed(2)}</td>
            <td class="text-right" style="font-weight: bold;">\${getCurrencySymbol(invoice.currency)}\${itm.amount.toFixed(2)}</td>
          </tr>
        \`).join('')}
      </tbody>
    </table>

    <div class="totals">
      <div class="totals-line">
        <span>Subtotal</span>
        <span>\${getCurrencySymbol(invoice.currency)}\${invoice.subtotal.toFixed(2)}</span>
      </div>
      <div class="totals-line">
        <span>Discount (\${invoice.discountRate}%)</span>
        <span>-\&nbsp;\${getCurrencySymbol(invoice.currency)}\${invoice.discountAmount.toFixed(2)}</span>
      </div>
      <div class="totals-line">
        <span>Tax (\${invoice.taxRate}%)</span>
        <span>+\${getCurrencySymbol(invoice.currency)}\${invoice.taxAmount.toFixed(2)}</span>
      </div>
      <div class="totals-line totals-grand">
        <span>Total Balance</span>
        <span>\${getCurrencySymbol(invoice.currency)}\${invoice.total.toFixed(2)}</span>
      </div>
    </div>

    \${invoice.notes ? \`<div class="notes"><strong>Official Notes:</strong> \${invoice.notes}</div>\` : ''}

    <div class="footer">
      <span>SecuraInvoices &copy; 2026</span>
      <span>Generated via Secura Secure E-Billing System</span>
    </div>
  </div>
</body>
</html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `invoice-\${invoice.invoiceNumber}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Calculate dynamic stats
  const totalInvoiced = invoices.reduce((sum, inv) => sum + inv.total, 0);
  const totalPaid = invoices.filter(i => i.status === 'paid').reduce((sum, inv) => sum + inv.total, 0);
  const totalOutstanding = invoices.filter(i => i.status !== 'paid').reduce((sum, inv) => sum + inv.total, 0);

  const filteredInvoices = invoices.filter(inv => {
    const matchesSearch = inv.clientName.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          inv.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = activeStatus === 'All' || inv.status === activeStatus.toLowerCase();
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Top action header */}
      <div className="flex items-center justify-between border-b border-zinc-100 dark:border-zinc-800/80 pb-6">
        <div>
          <h2 className="text-2xl font-black text-zinc-900 dark:text-zinc-50 tracking-tight">Invoice Generator</h2>
          <p className="text-zinc-500 text-sm mt-1">Design, audit, and distribute tax-compliant freelancer client invoices.</p>
        </div>
        <button 
          onClick={() => { resetForm(); setShowModal(true); }}
          className="px-4 py-2 rounded-lg bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-50 dark:hover:bg-zinc-200 text-white dark:text-zinc-950 text-xs font-bold transition-all shadow flex items-center gap-2 cursor-pointer"
        >
          <Plus className="w-4 h-4" />
          <span>Create Invoice</span>
        </button>
      </div>

      {/* Analytics widgets */}
      <div className="grid md:grid-cols-3 gap-5">
        <div className="p-6 rounded-2xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-zinc-50 dark:bg-zinc-950 text-zinc-800 dark:text-zinc-200 flex items-center justify-center">
            <DollarSign className="w-5 h-5 text-indigo-500" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 font-bold uppercase">Total Invoiced</div>
            <div className="text-2xl font-black text-zinc-900 dark:text-zinc-50 mt-1">${totalInvoiced.toFixed(2)}</div>
          </div>
        </div>

        <div className="p-6 rounded-2xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-zinc-50 dark:bg-zinc-950 text-zinc-800 dark:text-zinc-200 flex items-center justify-center">
            <Check className="w-5 h-5 text-emerald-500" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 font-bold uppercase">Collected Earnings</div>
            <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mt-1">${totalPaid.toFixed(2)}</div>
          </div>
        </div>

        <div className="p-6 rounded-2xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-zinc-50 dark:bg-zinc-950 text-zinc-800 dark:text-zinc-200 flex items-center justify-center">
            <Clock className="w-5 h-5 text-amber-500" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 font-bold uppercase">Outstanding Receivables</div>
            <div className="text-2xl font-black text-amber-600 dark:text-amber-400 mt-1">${totalOutstanding.toFixed(2)}</div>
          </div>
        </div>
      </div>

      {/* Invoices list container */}
      <div className="space-y-5">
        
        {/* Left Side Invoices list */}
        <div className="space-y-5">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-1.5">
              {['All', 'Paid', 'Sent'].map((status, i) => (
                <button 
                  key={i}
                  onClick={() => setActiveStatus(status)}
                  className={`px-3 py-1 rounded-lg text-xs font-semibold ${
                    activeStatus === status 
                      ? 'bg-zinc-900 dark:bg-zinc-50 text-white dark:text-zinc-950 font-bold' 
                      : 'text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800'
                  }`}
                >
                  {status}
                </button>
              ))}
            </div>

            <div className="relative w-44">
              <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-zinc-400">
                <Search className="w-3.5 h-3.5" />
              </span>
              <input 
                type="text" 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search Client..."
                className="w-full pl-8 pr-3 py-1.5 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none placeholder-zinc-400"
              />
            </div>
          </div>

          {loading ? (
            <div className="py-12 text-center text-xs text-zinc-400">Syncing billing logs...</div>
          ) : filteredInvoices.length === 0 ? (
            <div className="p-12 border border-dashed border-zinc-200 dark:border-zinc-800 rounded-2xl text-center text-xs text-zinc-400">
              No invoices created matching filters.
            </div>
          ) : (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredInvoices.map((inv, idx) => (
                <div 
                  key={idx}
                  onClick={() => setPreviewInvoice(inv)}
                  className="p-5 rounded-2xl border border-zinc-100 bg-white hover:border-zinc-900/40 hover:bg-zinc-50/30 dark:border-zinc-800 dark:bg-zinc-900 dark:hover:border-zinc-700 transition-all cursor-pointer flex items-center justify-between"
                >
                  <div>
                    <div className="font-bold text-zinc-900 dark:text-zinc-50 text-sm">{inv.clientName}</div>
                    <div className="text-[11px] text-zinc-400 mt-0.5">{inv.invoiceNumber} • Created {inv.createdDate}</div>
                  </div>
                  <div className="text-right">
                    <div className="font-black text-zinc-900 dark:text-zinc-50">
                      {getCurrencySymbol(inv.currency)}{inv.total.toFixed(2)}
                    </div>
                    <span className={`inline-block px-2 py-0.5 rounded text-[9px] font-extrabold uppercase mt-1 ${
                      inv.status === 'paid' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-400' : 'bg-amber-100 text-amber-800 dark:bg-amber-950/40 dark:text-amber-400'
                    }`}>
                      {inv.status}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>

      {/* Invoice PDF Viewer Modal Backdrop */}
      {previewInvoice && (
        <div 
          onClick={(e) => {
            if (!(e.target as HTMLElement).closest('.invoice-preview-content')) {
              setPreviewInvoice(null);
            }
          }}
          className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[80] flex items-center justify-center p-4 md:p-8 overflow-y-auto"
        >
          <div className="invoice-preview-content w-full max-w-4xl bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-2xl p-4 sm:p-6 md:p-8 max-h-[95vh] overflow-y-auto relative animate-scale-up">
            
            {/* Modal Header controls */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between border-b border-zinc-100 dark:border-zinc-800 pb-4 mb-6 sticky top-0 bg-white dark:bg-zinc-900 z-10 gap-3">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-indigo-500" />
                <span className="font-bold font-mono text-zinc-500 text-xs uppercase">Invoice PDF Workspace</span>
              </div>
              <div className="flex flex-wrap items-center gap-2 sm:gap-3">
                {/* Status Toggle buttons: Paid vs Pending */}
                <div className="flex items-center bg-zinc-100 dark:bg-zinc-800 p-1 rounded-lg border border-zinc-200/60 dark:border-zinc-700">
                  <button 
                    onClick={() => handleUpdateStatus(previewInvoice.id, 'sent')}
                    className={`px-3 py-1 rounded-md text-[10px] font-extrabold uppercase transition-all duration-200 cursor-pointer ${
                      previewInvoice.status !== 'paid' 
                        ? 'bg-amber-500 text-white shadow-sm' 
                        : 'text-zinc-500 dark:text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-300'
                    }`}
                  >
                    Pending
                  </button>
                  <button 
                    onClick={() => handleUpdateStatus(previewInvoice.id, 'paid')}
                    className={`px-3 py-1 rounded-md text-[10px] font-extrabold uppercase transition-all duration-200 cursor-pointer ${
                      previewInvoice.status === 'paid' 
                        ? 'bg-emerald-600 text-white shadow-sm' 
                        : 'text-zinc-500 dark:text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-300'
                    }`}
                  >
                    Paid
                  </button>
                </div>

                {/* Print / Save PDF button */}
                <button 
                  onClick={handlePrint}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-50 dark:hover:bg-zinc-200 text-white dark:text-zinc-950 text-xs font-bold transition-all shadow cursor-pointer"
                  title="Print / Save PDF"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>Print / Save PDF</span>
                </button>

                {/* Backup Download HTML button */}
                <button 
                  onClick={() => handleDownloadPDF(previewInvoice)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-800 text-zinc-700 dark:text-zinc-300 text-xs font-bold transition-all cursor-pointer"
                  title="Download HTML Backup"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>HTML Backup</span>
                </button>

                {/* Delete button */}
                <button 
                  onClick={() => handleDelete(previewInvoice.id)}
                  className="p-2 rounded-lg border border-zinc-200 dark:border-zinc-800 text-zinc-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/20 transition-all cursor-pointer"
                  title="Delete Invoice"
                >
                  <Trash2 className="w-4 h-4" />
                </button>

                {/* Close Button */}
                <button 
                  onClick={() => setPreviewInvoice(null)}
                  className="p-2 rounded-lg border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800 text-zinc-500 dark:text-zinc-400 font-bold transition-all cursor-pointer"
                  title="Close Preview"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Printable frame section */}
            <div className="overflow-x-auto w-full pb-4">
              <div 
                className="p-6 sm:p-10 rounded-xl bg-white text-black printable-area shadow-lg space-y-4 font-sans border border-zinc-200 max-w-[794px] w-full mx-auto" 
                style={{ color: '#000000', backgroundColor: '#ffffff', minHeight: '1000px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}
              >
                <div className="space-y-4 flex-1">
                  {/* Header: Title and QR Code */}
                  <div className="flex justify-between items-center pb-2 border-b border-zinc-100">
                    <div>
                      <h1 className="text-3xl font-black tracking-tight leading-none text-zinc-900" style={{ fontFamily: 'var(--font-sans)', fontWeight: 900 }}>
                        SECURA<br />INVOICE
                      </h1>
                    </div>
                    <div className="flex flex-col items-center">
                      <div className="p-1.5 border-2 border-zinc-900 rounded bg-white">
                        <QrCode className="w-12 h-12 text-zinc-900" strokeWidth={1.5} />
                      </div>
                      <span className="text-[8px] font-mono mt-0.5 text-zinc-500 uppercase tracking-widest">Digital Auth QR</span>
                    </div>
                  </div>

                  {/* Sender Information Block */}
                  <div className="flex flex-col sm:grid sm:grid-cols-2 gap-4 text-[11px] sm:text-xs pt-1">
                    <div className="space-y-1">
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Company:</span>
                        <span className="text-zinc-800">Secura Inc.</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Address:</span>
                        <span className="text-zinc-800">75 Financial Plaza, Suite 400</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">PostCode / City:</span>
                        <span className="text-zinc-800">10005 New York</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Location:</span>
                        <span className="text-zinc-800">United States</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Sender Name:</span>
                        <span className="text-zinc-800">Finance & Billing Dept</span>
                      </div>
                    </div>

                    <div className="space-y-1">
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Telephone / E-mail:</span>
                        <span className="text-zinc-800 font-mono">support@secura.io</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Shipping Date:</span>
                        <span className="text-zinc-800">{previewInvoice.createdDate}</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Shipping Number:</span>
                        <span className="text-zinc-800 font-mono">SHP-{previewInvoice.invoiceNumber.split('-')[1] || "49102"}</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Sender VAT Number:</span>
                        <span className="text-zinc-800 font-mono">VAT-US-8920193</span>
                      </div>
                    </div>
                  </div>

                  {/* Main black horizontal line divider */}
                  <div className="border-t border-zinc-900 my-2"></div>

                  {/* Receiver and Invoice Metadata Section */}
                  <div className="flex flex-col sm:grid sm:grid-cols-2 gap-4 text-[11px] sm:text-xs">
                    {/* Left: Send To */}
                    <div className="space-y-1">
                      <div className="font-black text-xs uppercase tracking-wider text-zinc-900 mb-1">Send To</div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Receiver Name:</span>
                        <span className="text-zinc-800">{previewInvoice.clientName}</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Address:</span>
                        <span className="text-zinc-800">{previewInvoice.clientAddress || "742 Evergreen Terrace"}</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Location:</span>
                        <span className="text-zinc-800">United States</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">PostCode / City:</span>
                        <span className="text-zinc-800">90210 California</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Telephone / E-mail:</span>
                        <span className="text-zinc-800 font-mono">{previewInvoice.clientEmail}</span>
                      </div>
                      <div className="grid grid-cols-[100px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Receiver VAT Number:</span>
                        <span className="text-zinc-800 font-mono font-bold">VAT-CL-3829103</span>
                      </div>
                    </div>

                    {/* Right: Invoice metadata details */}
                    <div className="space-y-1 sm:pt-5">
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Invoice Number:</span>
                        <span className="text-zinc-900 font-extrabold font-mono">{previewInvoice.invoiceNumber}</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Date:</span>
                        <span className="text-zinc-800 font-mono">{previewInvoice.createdDate}</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Order Number:</span>
                        <span className="text-zinc-800 font-mono">ORD-{previewInvoice.invoiceNumber.split('-')[1] || "28491"}</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Country of Origin:</span>
                        <span className="text-zinc-800">United States</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Destination Country:</span>
                        <span className="text-zinc-800">United States</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Terms of Payment:</span>
                        <span className="text-zinc-800">Net 30 Days</span>
                      </div>
                      <div className="grid grid-cols-[120px_1fr] leading-tight">
                        <span className="font-bold text-zinc-900">Bill of Lading:</span>
                        <span className="text-zinc-800 font-mono">BL-39201938</span>
                      </div>
                    </div>
                  </div>

                  {/* Table with grid borders wrapped in overflow-x container for mobile-friendliness */}
                  <div className="pt-2 overflow-x-auto w-full">
                    <table className="w-full border-collapse border border-zinc-900 text-[11px] sm:text-xs min-w-[500px]">
                      <thead>
                        <tr className="bg-zinc-50 border-b border-zinc-900 text-zinc-900 font-bold font-mono">
                          <th className="border border-zinc-900 p-2 text-left font-black">Description</th>
                          <th className="border border-zinc-900 p-2 text-center w-20 font-black">Quantity</th>
                          <th className="border border-zinc-900 p-2 text-right w-28 font-black">Unit price</th>
                          <th className="border border-zinc-900 p-2 text-right w-32 font-black">Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        {previewInvoice.items.map((itm: any, i: number) => (
                          <tr key={i} className="text-zinc-900 border-b border-zinc-900 font-mono">
                            <td className="border border-zinc-900 p-2 text-left font-sans">{itm.description}</td>
                            <td className="border border-zinc-900 p-2 text-center">{itm.quantity}</td>
                            <td className="border border-zinc-900 p-2 text-right">{getCurrencySymbol(previewInvoice.currency)}{itm.rate.toFixed(2)}</td>
                            <td className="border border-zinc-900 p-2 text-right font-bold">{getCurrencySymbol(previewInvoice.currency)}{itm.amount.toFixed(2)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  {/* Calculation breakdown: Subtotal, Discount, Tax, Total */}
                  <div className="space-y-1 pt-2 text-[11px] sm:text-xs font-mono w-full sm:max-w-sm sm:ml-auto">
                    <div className="flex justify-between border-b border-zinc-300 pb-1">
                      <span className="font-bold text-zinc-900">Subtotal</span>
                      <span className="text-zinc-800 font-bold">{getCurrencySymbol(previewInvoice.currency)}{previewInvoice.subtotal.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between border-b border-zinc-300 pb-1">
                      <span className="font-bold text-zinc-900">Discount ({previewInvoice.discountRate}%)</span>
                      <span className="text-zinc-800 font-bold">{previewInvoice.discountAmount > 0 ? '-' : ''}{getCurrencySymbol(previewInvoice.currency)}{previewInvoice.discountAmount.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between border-b border-zinc-300 pb-1">
                      <span className="font-bold text-zinc-900">Tax ({previewInvoice.taxRate}%)</span>
                      <span className="text-zinc-800 font-bold">+{getCurrencySymbol(previewInvoice.currency)}{previewInvoice.taxAmount.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between border-b-4 border-double border-zinc-900 py-1 text-xs sm:text-sm">
                      <span className="font-black text-zinc-950 uppercase">Total Balance</span>
                      <span className="font-black text-zinc-950 text-sm sm:text-base">{getCurrencySymbol(previewInvoice.currency)}{previewInvoice.total.toFixed(2)}</span>
                    </div>
                  </div>

                  {/* Notes and status badge */}
                  <div className="pt-2 flex flex-col sm:flex-row sm:justify-between sm:items-start gap-3 text-[11px] sm:text-xs">
                    <div className="max-w-md w-full">
                      {previewInvoice.notes && (
                        <div className="p-2.5 bg-zinc-50 border border-zinc-300 rounded text-[10px] sm:text-[11px] text-zinc-600 font-sans italic">
                          <strong className="block text-zinc-900 font-bold uppercase tracking-wider text-[9px] font-mono not-italic mb-0.5">Official Notes:</strong>
                          {previewInvoice.notes}
                        </div>
                      )}
                    </div>
                    <div className="text-left sm:text-right shrink-0">
                      <div className="font-bold text-[9px] sm:text-[10px] text-zinc-500 uppercase font-mono">Invoice Status</div>
                      <span className={`inline-block px-2.5 py-0.5 rounded text-[10px] sm:text-[11px] font-extrabold uppercase mt-0.5 tracking-wider ${
                        previewInvoice.status === 'paid' 
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300' 
                          : 'bg-amber-100 text-amber-800 border border-amber-300'
                      }`}>
                        {previewInvoice.status === 'paid' ? 'Paid' : 'Pending'}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Footer Logo - OnlineInvoices style */}
                <div className="pt-4 border-t border-zinc-200 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mt-8">
                  <div className="flex items-center gap-1.5">
                    {/* The green & black square logo from the template */}
                    <div className="flex items-center justify-center w-5 h-5 rounded bg-zinc-900 text-white font-black text-[10px]">
                      S
                    </div>
                    <span className="font-sans font-extrabold text-sm tracking-tight text-zinc-900">
                      Secura<span className="text-emerald-500 font-extrabold">Invoices</span>
                    </span>
                  </div>
                  <span className="text-[9px] font-mono text-zinc-400">
                    Generated via Secura Secure E-Billing System
                  </span>
                </div>

              </div>
            </div>

          </div>
        </div>
      )}

      {/* Create Invoice Modal Dialog */}
      {showModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 overflow-y-auto">
          <div className="w-full max-w-2xl bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-2xl p-6 md:p-8 animate-scale-up max-h-[90vh] overflow-y-auto">
            
            <div className="flex items-center justify-between border-b border-zinc-100 dark:border-zinc-800 pb-4 mb-6">
              <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-50">Create Client Invoice</h3>
              <button onClick={() => setShowModal(false)} className="p-1 rounded text-zinc-400">
                <X className="w-5 h-5" />
              </button>
            </div>

            {formError && (
              <div className="mb-4 p-3 rounded-lg bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900/50 text-xs font-bold text-red-600 dark:text-red-400 flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-red-500 shrink-0" />
                <span>{formError}</span>
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-6">
              
              {/* Client section */}
              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Client Name</label>
                  <input 
                    type="text" 
                    value={clientName}
                    onChange={(e) => setClientName(e.target.value)}
                    placeholder="e.g. Acme Corp"
                    className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Client Email</label>
                  <input 
                    type="email" 
                    value={clientEmail}
                    onChange={(e) => setClientEmail(e.target.value)}
                    placeholder="billing@acme.com"
                    className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-3 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Due Date</label>
                  <input 
                    type="date" 
                    value={dueDate}
                    onChange={(e) => setDueDate(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Currency</label>
                  <select 
                    value={currency} 
                    onChange={(e) => setCurrency(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none"
                  >
                    <option value="USD">USD ($)</option>
                    <option value="EUR">EUR (€)</option>
                    <option value="GBP">GBP (£)</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Tax Rate (%)</label>
                  <input 
                    type="number" 
                    value={taxRate}
                    onChange={(e) => setTaxRate(Number(e.target.value))}
                    className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none"
                  />
                </div>
              </div>

              {/* Multiple item addition framework */}
              <div className="space-y-3">
                <div className="flex items-center justify-between border-b border-zinc-100 dark:border-zinc-800 pb-2">
                  <span className="text-[10px] font-bold text-zinc-400 uppercase">Invoice Line Items</span>
                  <button 
                    type="button" 
                    onClick={handleAddItem}
                    className="text-[10px] text-indigo-500 font-bold hover:underline"
                  >
                    + Add Item
                  </button>
                </div>

                <div className="space-y-2">
                  {items.map((itm, i) => (
                    <div key={i} className="flex items-center gap-3">
                      <input 
                        type="text" 
                        value={itm.description}
                        onChange={(e) => handleItemChange(i, 'description', e.target.value)}
                        placeholder="Description of work..."
                        className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none"
                      />
                      <input 
                        type="number" 
                        value={itm.quantity}
                        onChange={(e) => handleItemChange(i, 'quantity', e.target.value)}
                        placeholder="Qty"
                        className="w-20 px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none text-center"
                      />
                      <input 
                        type="number" 
                        value={itm.rate}
                        onChange={(e) => handleItemChange(i, 'rate', e.target.value)}
                        placeholder="Rate"
                        className="w-24 px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none text-right"
                      />
                      <button 
                        type="button" 
                        onClick={() => handleRemoveItem(i)}
                        className="text-zinc-400 hover:text-rose-500"
                        disabled={items.length === 1}
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-bold text-zinc-400 uppercase">Notes / Payment Instructions</label>
                <textarea 
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="e.g. Please wire to Routing: xxxxx, Account: xxxxx"
                  rows={2}
                  className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-800 dark:text-zinc-100 text-xs focus:outline-none resize-none"
                />
              </div>

              {formError && (
                <div className="p-3 rounded-lg bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900/50 text-xs font-bold text-red-600 dark:text-red-400 flex items-center gap-2 animate-pulse">
                  <AlertCircle className="w-4 h-4 text-red-500 shrink-0" />
                  <span>{formError}</span>
                </div>
              )}

              <div className="pt-4 flex items-center justify-end gap-3 border-t border-zinc-100 dark:border-zinc-800">
                <button 
                  type="button" 
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 rounded-lg border border-zinc-200 hover:bg-zinc-50 text-xs font-bold text-zinc-500 transition-all"
                >
                  Cancel
                </button>
                <button 
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-50 dark:hover:bg-zinc-200 text-white dark:text-zinc-950 text-xs font-bold transition-all shadow"
                >
                  Generate Invoice
                </button>
              </div>

            </form>
          </div>
        </div>
      )}

      {/* SEO-Optimized FAQ Section with JSON-LD Schema */}
      <script 
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdData) }}
      />
      <div className="mt-16 border-t border-zinc-100 dark:border-zinc-800/80 pt-12 max-w-4xl mx-auto">
        <div className="text-center mb-10">
          <h3 className="text-xl font-extrabold text-zinc-900 dark:text-zinc-50 tracking-tight">
            Frequently Asked Questions (FAQ)
          </h3>
          <p className="text-zinc-500 text-xs mt-2">
            Have questions about freelancer invoicing, tax-ready billing sheets, or PDF generation? Find answers here.
          </p>
        </div>

        <div className="space-y-3">
          {faqData.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div 
                key={idx} 
                className="rounded-2xl border border-zinc-100 dark:border-zinc-800/60 bg-white dark:bg-zinc-900/30 overflow-hidden transition-all duration-200"
              >
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  className="w-full px-6 py-4 flex items-center justify-between text-left font-bold text-zinc-800 dark:text-zinc-100 hover:bg-zinc-50 dark:hover:bg-zinc-900/50 transition-colors text-xs cursor-pointer select-none"
                >
                  <span>{faq.q}</span>
                  <ChevronDown 
                    className={`w-4 h-4 text-zinc-400 shrink-0 transition-transform duration-200 ${isOpen ? 'rotate-180 text-zinc-700 dark:text-zinc-200' : ''}`} 
                  />
                </button>
                
                {isOpen && (
                  <div className="px-6 pb-5 pt-1 text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed border-t border-zinc-50 dark:border-zinc-800/30 animate-fade-in">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* 600+ Words SEO-Optimized Article Section */}
      <article className="mt-20 border-t border-zinc-100 dark:border-zinc-800/80 pt-16 max-w-4xl mx-auto text-zinc-700 dark:text-zinc-300">
        <header className="mb-8">
          <span className="text-[10px] font-bold tracking-widest text-zinc-400 uppercase">SEO Insights & Guide</span>
          <h3 className="text-2xl font-black text-zinc-900 dark:text-zinc-50 mt-1 leading-none tracking-tight">
            Ultimate Guide to Invoicing: Why Secura is the Best Free Invoice Maker for Solopreneurs
          </h3>
        </header>

        <div className="space-y-6 text-xs leading-relaxed">
          <p>
            In the modern digital economy, staying competitive as a freelancer, consultant, or small business operator demands absolute precision in your administrative workflows. While a robust <strong className="text-zinc-900 dark:text-zinc-100">personal planner</strong> helps map out your day-to-day productivity milestones, managing accounts receivable cleanly is what keeps your operation funded. That is where Secura's premium, zero-cost <strong className="text-zinc-900 dark:text-zinc-100">free invoice generator</strong> steps in. Engineered to be the absolute <strong className="text-zinc-900 dark:text-zinc-100">best free invoice maker</strong> on the web, Secura bridges the gap between client communication and payment resolution by automating the creation of pristine billing documents.
          </p>

          <p>
            Many professionals initially make the mistake of using standard text processors or unformatted spreadsheets to bill their clients. However, manual calculation errors, missing payment identifiers, and unprofessional layouts often trigger long delays in corporate finance departments. To avoid these common setbacks, utilizing an <strong className="text-zinc-900 dark:text-zinc-100">online invoice generator</strong> built with automatic calculation triggers is the absolute <strong className="text-zinc-900 dark:text-zinc-100">invoice generator best</strong> practice. Our platform serves as a completely <strong className="text-zinc-900 dark:text-zinc-100">simple invoice generator</strong> that eliminates mathematical errors and tax computation slip-ups, allowing you to <strong className="text-zinc-900 dark:text-zinc-100">create invoice online free PDF</strong> records that your clients can pay instantly.
          </p>

          <p>
            As a dynamic, all-in-one productivity hub, Secura acts as a reliable <strong className="text-zinc-900 dark:text-zinc-100">freelancer invoice generator</strong>. Our interface ensures that you can format and customize each document to match your specific professional branding guidelines. Rather than committing to costly monthly bookkeeping subscriptions, you can run your business with our top-rated <strong className="text-zinc-900 dark:text-zinc-100">free invoice maker app</strong>. Our specialized <strong className="text-zinc-900 dark:text-zinc-100">invoice generator software</strong> provides full-service billing automation at zero cost. That is why industry professionals rate Secura as the <strong className="text-zinc-900 dark:text-zinc-100">best invoice app free</strong> from subscriptions, unlocking unlimited generation capabilities so you can <strong className="text-zinc-900 dark:text-zinc-100">create invoice online free</strong> of constraints.
          </p>

          <div className="my-8 p-6 rounded-2xl bg-zinc-50 dark:bg-zinc-900/40 border border-zinc-100 dark:border-zinc-800/60">
            <h4 className="text-xs font-bold text-zinc-900 dark:text-zinc-50 uppercase tracking-wider mb-3">
              Essential Components of a Tax-Ready Professional Invoice
            </h4>
            <ul className="space-y-2 list-disc list-inside text-zinc-600 dark:text-zinc-400">
              <li>
                <strong className="text-zinc-800 dark:text-zinc-200">Header Identifiers</strong>: Distinct labels stating "Invoice" along with a unique document index code to help clients track their payables cleanly.
              </li>
              <li>
                <strong className="text-zinc-800 dark:text-zinc-200">Contact Specifics</strong>: Accurate email, phone numbers, and physical addresses of both the sender and the client company.
              </li>
              <li>
                <strong className="text-zinc-800 dark:text-zinc-200">Line-by-Line Itemization</strong>: Structured summaries detailing tasks completed, hourly rates, physical units, sub-totals, and specific tax percentages.
              </li>
              <li>
                <strong className="text-zinc-800 dark:text-zinc-200">Clear Payment Guidelines</strong>: Explicit instructions regarding bank routing, online wire transfers, or direct payment portal links to prevent late fees.
              </li>
            </ul>
          </div>

          <p>
            Furthermore, the capability to quickly <strong className="text-zinc-900 dark:text-zinc-100">create invoice online free PDF</strong> sheets means you can download your bills to any local machine and transmit them as clean email attachments instantly. Since our tool is fully mobile-responsive, you can generate new client statements directly from your smartphone while traveling, making it the perfect mobile invoicing asset. Your sensitive accounting data is securely handled, and because it is client-side, only you have access to your private earnings figures.
          </p>

          <p>
            Whether you are issuing your first single-item invoice or running a large-scale freelancing contract, Secura's <strong className="text-zinc-900 dark:text-zinc-100">invoice generator</strong> simplifies your life. Say goodbye to complex accounting software and experience the freedom of elite, automatic billing. By pairing your financial logs with our integrated budget managers and expiration checkers, you create a seamless workspace that supports your professional growth. Join hundreds of self-employed freelancers who rely on Secura to manage their client invoices without paying premium processing fees.
          </p>
        </div>
      </article>

    </div>
  );
}
